import { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";
import FlowerCanvas from "@/components/layout/flower";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Ayan Mammadova",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,200..800;1,6..72,200..800&display=swap" rel="stylesheet" />
      </head>
      <ThemeProvider attribute="class" defaultTheme="system">
        <body className="antialiased">
          <Header />
          {children}
          {/* <FlowerCanvas /> */}
        </body>
      </ThemeProvider>

    </html>
  );
}